openapi: 3.0.2
info:
  title: Apollo
  version: '0'
  description: Generates bus routes
  contact:
    name: Neel Kamath
    email: neelkamath@icloud.com
    url: https://github.com/neelkamath/apollo
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://apollo.herokuapp.com
    description: This is a temporary development server which may be offline or serving a different API in the future.
paths:
  /tag:
    get:
      tags: [tag]
      description: Gets all tags
      operationId: getTags
      responses:
        200:
          $ref: '#/components/responses/TagsResponse'
    post:
      tags: [tag]
      description: Create a tag
      operationId: createTag
      requestBody:
        content:
          application/json:
            example:
              tag: 2nd Semester
            schema:
              type: object
              properties:
                tag:
                  type: string
              required: [tag]
      responses:
        204:
          description: Created tag
    delete:
      tags: [tag]
      description: Delete tag
      operationId: deleteTag
      requestBody:
        content:
          application/json:
            example:
              tag: 2nd Semester
            schema:
              type: object
              properties:
                tag:
                  type: string
              required: [tag]
      responses:
        204:
          description: Tag deleted
  /user:
    get:
      tags: [user]
      description: Gets all users
      operationId: getUsers
      responses:
        200:
          $ref: '#/components/responses/UsersResponse'
    post:
      tags: [user]
      description: Create a user
      operationId: createUser
      requestBody:
        content:
          application/json:
            example:
              name: Neel Kamath
              id: PES2201800467
              address: 311/3, 23rd Cross, 2nd Main, 6th Block, Jayanagar, Bangalore, Karnataka, India
              longitude: 77.6727
              latitude: 12.8458
              tags: [2nd Year, CSE]
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: string
                address:
                  type: string
                longitude:
                  type: number
                latitude:
                  type: number
                tags:
                  type: array
                  items:
                    type: string
              required: [name, id, tags, address, longitude, latitude]
      responses:
        204:
          description: Created user
    delete:
      tags: [user]
      description: Delete user
      operationId: deleteUser
      requestBody:
        content:
          application/json:
            example:
              id: PES2201800467
            schema:
              type: object
              properties:
                id:
                  type: string
              required: [id]
      responses:
        204:
          description: User deleted
  /generate:
    post:
      tags: [generate]
      description: Generate bus routes
      operationId: generateRoute
      requestBody:
        content:
          application/json:
            example:
              address: PESU, Electronic City Campus
              longitude: 77.6727
              latitude: 12.8458
              tags: [CSE, 2nd Semester]
            schema:
              type: object
              properties:
                address:
                  description: The address of the college, etc. the buses are being driven to
                  type: string
                longitude:
                  description: The longitude of the college, etc. the buses are being driven to
                  type: number
                latitude:
                  description: The latitude of the college, etc. the buses are being driven to
                  type: number
                tags:
                  description: The bus routes will be generated only for people having these tags.
                  type: array
                  items:
                    type: string
              required: [tags, address, longitude, latitude]
      responses:
        200:
          description: Generated routes
          content:
            application/json:
              example:
                routes:
                  - route: 1
                    passengers:
                      - id: PES2201800467
                        longitude: 77.56029
                        latitude: 12.97021
                        proximity: CLOSE
              schema:
                type: object
                properties:
                  routes:
                    type: array
                    items:
                      type: object
                      properties:
                        route:
                          type: integer
                          description: Route number
                        passengers:
                          type: array
                          description: Passengers of this vehicle's route
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                                description: Passenger's ID
                              longitude:
                                type: number
                                description: The longitude of the passenger's residence
                              latitude:
                                type: number
                                description: The latitude of the passenger's residence
                              proximity:
                                type: string
                                enum: [CLOSE, NORMAL, FAR]
                                description:
                                  Whether the passenger's residence is a `"CLOSE"`, `"NORMAL"`, or `"FAR"` distance from
                                  the institute
                            required: [id, longitude, latitude, proximity]
                      required: [route, passengers]
                required: [routes]
  /eta:
    get:
      tags: [eta]
      description: The estimated time of arrival
      operationId: eta
      parameters:
        - in: query
          name: current_longitude
          required: true
          schema:
            type: number
          description: Longitude of the place they are currently in
        - in: query
          name: current_latitude
          required: true
          schema:
            type: number
          description: Latitude of the place they are currently in
        - in: query
          name: destination_longitude
          required: true
          schema:
            type: number
          description: Longitude of the destination
        - in: query
          name: destination_latitude
          required: true
          schema:
            type: number
          description: Latitude of the destination
      responses:
        200:
          description: ETA
          content:
            application/json:
              schema:
                type: object
                example:
                  eta: 135
                properties:
                  eta:
                    type: number
                    description: Number of seconds to destination
                required: [eta]
components:
  responses:
    TagsResponse:
      description: Every tag
      content:
        application/json:
          schema:
            example:
              tags: [CSE, 3rd Semester, 7th Semester, ME]
            type: object
            properties:
              tags:
                type: array
                items:
                  type: string
            required: [tags]
    UsersResponse:
      description: Every user
      content:
        application/json:
          schema:
            example:
              users:
                - name: Neel Kamath
                  id: PES2201800467
                  address: 311/3, 23rd Cross, 2nd Main, 6th Block, Jayanagar, Bangalore, Karnataka, India
                  longitude: 77.6727
                  latitude: 12.8458
                  tags: [CSE, 2nd Year]
            properties:
              users:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    id:
                      type: string
                    address:
                      type: string
                    longitude:
                      type: number
                    latitude:
                      type: number
                    tags:
                      type: array
                      items:
                        type: string
                  required: [name, id, tags, address, longitude, latitude]
            required: [users]